// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>ECM.Communication</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>True</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace ECM.Communication
{
	using System;
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System.Collections;
	using System.Xml.Schema;
	using System.ComponentModel;
	using System.Xml;
	using System.Collections.Generic;


	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Header
	{

		private DocumentType documentField;

		private List<TaskListTypeTask> taskListField;

		private List<AddDocumentsTypeFolder> addDocumentsField;

		private ExpansionType expansionField;

		private AcknowledgementType acknowledgementField;

		private string standartField;

		private string versionField;

		private System.DateTime timeField;

		private sbyte msg_typeField;

		private string msg_idField;

		private sbyte msg_acknowField;

		private string from_org_idField;

		private string from_organizationField;

		private string from_departmentField;

		private string from_sys_idField;

		private string from_systemField;

		private string from_system_detailsField;

		private string to_org_idField;

		private string to_organizationField;

		private string to_departmentField;

		private string to_sys_idField;

		private string to_systemField;

		private string to_system_detailsField;

		public Header()
		{
			this.acknowledgementField = new AcknowledgementType();
			this.expansionField = new ExpansionType();
			this.addDocumentsField = new List<AddDocumentsTypeFolder>();
			this.taskListField = new List<TaskListTypeTask>();
			this.documentField = new DocumentType();
			this.msg_acknowField = ((sbyte) (0));
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public DocumentType Document
		{
			get
			{
				return this.documentField;
			}
			set
			{
				this.documentField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Task", IsNullable = false)]
		public List<TaskListTypeTask> TaskList
		{
			get
			{
				return this.taskListField;
			}
			set
			{
				this.taskListField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
		[System.Xml.Serialization.XmlArrayItemAttribute("Folder", IsNullable = false)]
		public List<AddDocumentsTypeFolder> AddDocuments
		{
			get
			{
				return this.addDocumentsField;
			}
			set
			{
				this.addDocumentsField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public ExpansionType Expansion
		{
			get
			{
				return this.expansionField;
			}
			set
			{
				this.expansionField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public AcknowledgementType Acknowledgement
		{
			get
			{
				return this.acknowledgementField;
			}
			set
			{
				this.acknowledgementField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string standart
		{
			get
			{
				return this.standartField;
			}
			set
			{
				this.standartField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string version
		{
			get
			{
				return this.versionField;
			}
			set
			{
				this.versionField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public System.DateTime time
		{
			get
			{
				return this.timeField;
			}
			set
			{
				this.timeField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte msg_type
		{
			get
			{
				return this.msg_typeField;
			}
			set
			{
				this.msg_typeField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string msg_id
		{
			get
			{
				return this.msg_idField;
			}
			set
			{
				this.msg_idField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(typeof(sbyte), "0")]
		public sbyte msg_acknow
		{
			get
			{
				return this.msg_acknowField;
			}
			set
			{
				this.msg_acknowField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string from_org_id
		{
			get
			{
				return this.from_org_idField;
			}
			set
			{
				this.from_org_idField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string from_organization
		{
			get
			{
				return this.from_organizationField;
			}
			set
			{
				this.from_organizationField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string from_department
		{
			get
			{
				return this.from_departmentField;
			}
			set
			{
				this.from_departmentField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string from_sys_id
		{
			get
			{
				return this.from_sys_idField;
			}
			set
			{
				this.from_sys_idField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string from_system
		{
			get
			{
				return this.from_systemField;
			}
			set
			{
				this.from_systemField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string from_system_details
		{
			get
			{
				return this.from_system_detailsField;
			}
			set
			{
				this.from_system_detailsField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string to_org_id
		{
			get
			{
				return this.to_org_idField;
			}
			set
			{
				this.to_org_idField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string to_organization
		{
			get
			{
				return this.to_organizationField;
			}
			set
			{
				this.to_organizationField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string to_department
		{
			get
			{
				return this.to_departmentField;
			}
			set
			{
				this.to_departmentField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string to_sys_id
		{
			get
			{
				return this.to_sys_idField;
			}
			set
			{
				this.to_sys_idField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string to_system
		{
			get
			{
				return this.to_systemField;
			}
			set
			{
				this.to_systemField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string to_system_details
		{
			get
			{
				return this.to_system_detailsField;
			}
			set
			{
				this.to_system_detailsField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
	public partial class DocumentType
	{

		private RegNumber regNumberField;

		private Confident confidentField;

		private List<Referred> referredField;

		private List<DocNumber> docNumberField;

		private List<Addressee> addresseeField;

		private List<DocTransfer> docTransferField;

		private List<RegHistory> regHistoryField;

		private List<Author> authorField;

		private List<Validator> validatorField;

		private Writer writerField;

		private string idnumberField;

		private sbyte typeField;

		private string kindField;

		private ulong pagesField;

		private bool pagesFieldSpecified;

		private string titleField;

		private string annotationField;

		private sbyte collectionField;

		private bool collectionFieldSpecified;

		public DocumentType()
		{
			this.writerField = new Writer();
			this.validatorField = new List<Validator>();
			this.authorField = new List<Author>();
			this.regHistoryField = new List<RegHistory>();
			this.docTransferField = new List<DocTransfer>();
			this.addresseeField = new List<Addressee>();
			this.docNumberField = new List<DocNumber>();
			this.referredField = new List<Referred>();
			this.confidentField = new Confident();
			this.regNumberField = new RegNumber();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public RegNumber RegNumber
		{
			get
			{
				return this.regNumberField;
			}
			set
			{
				this.regNumberField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public Confident Confident
		{
			get
			{
				return this.confidentField;
			}
			set
			{
				this.confidentField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Referred", Order = 2)]
		public List<Referred> Referred
		{
			get
			{
				return this.referredField;
			}
			set
			{
				this.referredField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("DocNumber", Order = 3)]
		public List<DocNumber> DocNumber
		{
			get
			{
				return this.docNumberField;
			}
			set
			{
				this.docNumberField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Addressee", Order = 4)]
		public List<Addressee> Addressee
		{
			get
			{
				return this.addresseeField;
			}
			set
			{
				this.addresseeField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("DocTransfer", Order = 5)]
		public List<DocTransfer> DocTransfer
		{
			get
			{
				return this.docTransferField;
			}
			set
			{
				this.docTransferField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("RegHistory", Order = 6)]
		public List<RegHistory> RegHistory
		{
			get
			{
				return this.regHistoryField;
			}
			set
			{
				this.regHistoryField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Author", Order = 7)]
		public List<Author> Author
		{
			get
			{
				return this.authorField;
			}
			set
			{
				this.authorField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Validator", Order = 8)]
		public List<Validator> Validator
		{
			get
			{
				return this.validatorField;
			}
			set
			{
				this.validatorField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 9)]
		public Writer Writer
		{
			get
			{
				return this.writerField;
			}
			set
			{
				this.writerField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string idnumber
		{
			get
			{
				return this.idnumberField;
			}
			set
			{
				this.idnumberField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string kind
		{
			get
			{
				return this.kindField;
			}
			set
			{
				this.kindField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong pages
		{
			get
			{
				return this.pagesField;
			}
			set
			{
				this.pagesField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool pagesSpecified
		{
			get
			{
				return this.pagesFieldSpecified;
			}
			set
			{
				this.pagesFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string title
		{
			get
			{
				return this.titleField;
			}
			set
			{
				this.titleField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string annotation
		{
			get
			{
				return this.annotationField;
			}
			set
			{
				this.annotationField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte collection
		{
			get
			{
				return this.collectionField;
			}
			set
			{
				this.collectionField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool collectionSpecified
		{
			get
			{
				return this.collectionFieldSpecified;
			}
			set
			{
				this.collectionFieldSpecified = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class RegNumber
	{

		private System.DateTime regdateField;

		private string valueField;

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime regdate
		{
			get
			{
				return this.regdateField;
			}
			set
			{
				this.regdateField = value;
			}
		}

		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
	public partial class AcknowledgementType
	{

		private RegNumber regNumberField;

		private List<AckResult> ackResultField;

		private DocTransfer docTransferField;

		private string msg_idField;

		private sbyte ask_typeField;

		public AcknowledgementType()
		{
			this.docTransferField = new DocTransfer();
			this.ackResultField = new List<AckResult>();
			this.regNumberField = new RegNumber();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public RegNumber RegNumber
		{
			get
			{
				return this.regNumberField;
			}
			set
			{
				this.regNumberField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("AckResult", Order = 1)]
		public List<AckResult> AckResult
		{
			get
			{
				return this.ackResultField;
			}
			set
			{
				this.ackResultField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public DocTransfer DocTransfer
		{
			get
			{
				return this.docTransferField;
			}
			set
			{
				this.docTransferField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string msg_id
		{
			get
			{
				return this.msg_idField;
			}
			set
			{
				this.msg_idField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte ask_type
		{
			get
			{
				return this.ask_typeField;
			}
			set
			{
				this.ask_typeField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class AckResult
	{

		private ulong errorcodeField;

		private string valueField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong errorcode
		{
			get
			{
				return this.errorcodeField;
			}
			set
			{
				this.errorcodeField = value;
			}
		}

		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class DocTransfer
	{

		private string osField;

		private string typeField;

		private string type_verField;

		private string char_setField;

		private string descriptionField;

		private sbyte transfertypeField;

		private byte[] valueField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string os
		{
			get
			{
				return this.osField;
			}
			set
			{
				this.osField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type_ver
		{
			get
			{
				return this.type_verField;
			}
			set
			{
				this.type_verField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string char_set
		{
			get
			{
				return this.char_setField;
			}
			set
			{
				this.char_setField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string description
		{
			get
			{
				return this.descriptionField;
			}
			set
			{
				this.descriptionField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte transfertype
		{
			get
			{
				return this.transfertypeField;
			}
			set
			{
				this.transfertypeField = value;
			}
		}

		[System.Xml.Serialization.XmlTextAttribute(DataType = "base64Binary")]
		public byte[] Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
	public partial class ExpansionType
	{

		private List<Econtact> econtactField;

		private ExpansionTypeAnyData anyDataField;

		private string organizationField;

		private string exp_verField;

		public ExpansionType()
		{
			this.anyDataField = new ExpansionTypeAnyData();
			this.econtactField = new List<Econtact>();
		}

		[System.Xml.Serialization.XmlElementAttribute("Econtact", Order = 0)]
		public List<Econtact> Econtact
		{
			get
			{
				return this.econtactField;
			}
			set
			{
				this.econtactField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public ExpansionTypeAnyData AnyData
		{
			get
			{
				return this.anyDataField;
			}
			set
			{
				this.anyDataField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string organization
		{
			get
			{
				return this.organizationField;
			}
			set
			{
				this.organizationField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string exp_ver
		{
			get
			{
				return this.exp_verField;
			}
			set
			{
				this.exp_verField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Econtact
	{

		private sbyte typeField;

		private bool typeFieldSpecified;

		private string valueField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool typeSpecified
		{
			get
			{
				return this.typeFieldSpecified;
			}
			set
			{
				this.typeFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ExpansionTypeAnyData
	{

		private List<System.Xml.XmlElement> anyField;

		public ExpansionTypeAnyData()
		{
			this.anyField = new List<System.Xml.XmlElement>();
		}

		[System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
		public List<System.Xml.XmlElement> Any
		{
			get
			{
				return this.anyField;
			}
			set
			{
				this.anyField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Confident
	{

		private sbyte flagField;

		private string valueField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte flag
		{
			get
			{
				return this.flagField;
			}
			set
			{
				this.flagField = value;
			}
		}

		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Referred
	{

		private object itemField;

		private string idnumberField;

		private sbyte retypeField;

		private bool retypeFieldSpecified;

		[System.Xml.Serialization.XmlElementAttribute("RegNumber", typeof(RegNumber), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("TaskNumber", typeof(TaskNumber), Order = 0)]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string idnumber
		{
			get
			{
				return this.idnumberField;
			}
			set
			{
				this.idnumberField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte retype
		{
			get
			{
				return this.retypeField;
			}
			set
			{
				this.retypeField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool retypeSpecified
		{
			get
			{
				return this.retypeFieldSpecified;
			}
			set
			{
				this.retypeFieldSpecified = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class TaskNumber
	{

		private System.DateTime taskDateField;

		private string valueField;

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime taskDate
		{
			get
			{
				return this.taskDateField;
			}
			set
			{
				this.taskDateField = value;
			}
		}

		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class DocNumber
	{

		private OrganizationOnly organizationOnlyField;

		private RegNumber regNumberField;

		private string kindField;

		public DocNumber()
		{
			this.regNumberField = new RegNumber();
			this.organizationOnlyField = new OrganizationOnly();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public OrganizationOnly OrganizationOnly
		{
			get
			{
				return this.organizationOnlyField;
			}
			set
			{
				this.organizationOnlyField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public RegNumber RegNumber
		{
			get
			{
				return this.regNumberField;
			}
			set
			{
				this.regNumberField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string kind
		{
			get
			{
				return this.kindField;
			}
			set
			{
				this.kindField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class OrganizationOnly
	{

		private Address addressField;

		private List<Econtact> econtactField;

		private string organization_stringField;

		private string fullnameField;

		private string shortnameField;

		private string ownershipField;

		private ulong ogrnField;

		private bool ogrnFieldSpecified;

		private ulong innField;

		private bool innFieldSpecified;

		private ulong kppField;

		private bool kppFieldSpecified;

		public OrganizationOnly()
		{
			this.econtactField = new List<Econtact>();
			this.addressField = new Address();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Address Address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Econtact", Order = 1)]
		public List<Econtact> Econtact
		{
			get
			{
				return this.econtactField;
			}
			set
			{
				this.econtactField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string organization_string
		{
			get
			{
				return this.organization_stringField;
			}
			set
			{
				this.organization_stringField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string fullname
		{
			get
			{
				return this.fullnameField;
			}
			set
			{
				this.fullnameField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string shortname
		{
			get
			{
				return this.shortnameField;
			}
			set
			{
				this.shortnameField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string ownership
		{
			get
			{
				return this.ownershipField;
			}
			set
			{
				this.ownershipField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong ogrn
		{
			get
			{
				return this.ogrnField;
			}
			set
			{
				this.ogrnField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ogrnSpecified
		{
			get
			{
				return this.ogrnFieldSpecified;
			}
			set
			{
				this.ogrnFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong inn
		{
			get
			{
				return this.innField;
			}
			set
			{
				this.innField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool innSpecified
		{
			get
			{
				return this.innFieldSpecified;
			}
			set
			{
				this.innFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong kpp
		{
			get
			{
				return this.kppField;
			}
			set
			{
				this.kppField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool kppSpecified
		{
			get
			{
				return this.kppFieldSpecified;
			}
			set
			{
				this.kppFieldSpecified = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Address
	{

		private string streetField;

		private string houseField;

		private string buildingField;

		private string flatField;

		private string settlementField;

		private string districtField;

		private string regionField;

		private string countryField;

		private string postсodeField;

		private string postboxField;

		private string nontypicalField;

		private string valueField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string street
		{
			get
			{
				return this.streetField;
			}
			set
			{
				this.streetField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string house
		{
			get
			{
				return this.houseField;
			}
			set
			{
				this.houseField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string building
		{
			get
			{
				return this.buildingField;
			}
			set
			{
				this.buildingField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string flat
		{
			get
			{
				return this.flatField;
			}
			set
			{
				this.flatField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string settlement
		{
			get
			{
				return this.settlementField;
			}
			set
			{
				this.settlementField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string district
		{
			get
			{
				return this.districtField;
			}
			set
			{
				this.districtField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string region
		{
			get
			{
				return this.regionField;
			}
			set
			{
				this.regionField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string country
		{
			get
			{
				return this.countryField;
			}
			set
			{
				this.countryField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string postсode
		{
			get
			{
				return this.postсodeField;
			}
			set
			{
				this.postсodeField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string postbox
		{
			get
			{
				return this.postboxField;
			}
			set
			{
				this.postboxField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string nontypical
		{
			get
			{
				return this.nontypicalField;
			}
			set
			{
				this.nontypicalField = value;
			}
		}

		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Addressee
	{

		private List<object> itemsField;

		public Addressee()
		{
			this.itemsField = new List<object>();
		}

		[System.Xml.Serialization.XmlElementAttribute("Organization", typeof(Organization), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("PrivatePerson", typeof(PrivatePerson), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("Referred", typeof(Referred), Order = 0)]
		public List<object> Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Organization
	{

		private Address addressField;

		private List<Econtact> econtactField;

		private List<OfficialPerson> officialPersonField;

		private string organization_stringField;

		private string fullnameField;

		private string shortnameField;

		private string ownershipField;

		private ulong ogrnField;

		private bool ogrnFieldSpecified;

		private ulong innField;

		private bool innFieldSpecified;

		private ulong kppField;

		private bool kppFieldSpecified;

		public Organization()
		{
			this.officialPersonField = new List<OfficialPerson>();
			this.econtactField = new List<Econtact>();
			this.addressField = new Address();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Address Address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Econtact", Order = 1)]
		public List<Econtact> Econtact
		{
			get
			{
				return this.econtactField;
			}
			set
			{
				this.econtactField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("OfficialPerson", Order = 2)]
		public List<OfficialPerson> OfficialPerson
		{
			get
			{
				return this.officialPersonField;
			}
			set
			{
				this.officialPersonField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string organization_string
		{
			get
			{
				return this.organization_stringField;
			}
			set
			{
				this.organization_stringField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string fullname
		{
			get
			{
				return this.fullnameField;
			}
			set
			{
				this.fullnameField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string shortname
		{
			get
			{
				return this.shortnameField;
			}
			set
			{
				this.shortnameField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string ownership
		{
			get
			{
				return this.ownershipField;
			}
			set
			{
				this.ownershipField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong ogrn
		{
			get
			{
				return this.ogrnField;
			}
			set
			{
				this.ogrnField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ogrnSpecified
		{
			get
			{
				return this.ogrnFieldSpecified;
			}
			set
			{
				this.ogrnFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong inn
		{
			get
			{
				return this.innField;
			}
			set
			{
				this.innField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool innSpecified
		{
			get
			{
				return this.innFieldSpecified;
			}
			set
			{
				this.innFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong kpp
		{
			get
			{
				return this.kppField;
			}
			set
			{
				this.kppField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool kppSpecified
		{
			get
			{
				return this.kppFieldSpecified;
			}
			set
			{
				this.kppFieldSpecified = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class OfficialPerson
	{

		private Name nameField;

		private List<Official> officialField;

		private List<Rank> rankField;

		private Address addressField;

		private List<Econtact> econtactField;

		public OfficialPerson()
		{
			this.econtactField = new List<Econtact>();
			this.addressField = new Address();
			this.rankField = new List<Rank>();
			this.officialField = new List<Official>();
			this.nameField = new Name();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Name Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Official", Order = 1)]
		public List<Official> Official
		{
			get
			{
				return this.officialField;
			}
			set
			{
				this.officialField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Rank", Order = 2)]
		public List<Rank> Rank
		{
			get
			{
				return this.rankField;
			}
			set
			{
				this.rankField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public Address Address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Econtact", Order = 4)]
		public List<Econtact> Econtact
		{
			get
			{
				return this.econtactField;
			}
			set
			{
				this.econtactField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Name
	{

		private string secnameField;

		private string firstnameField;

		private string fathersnameField;

		private string valueField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string secname
		{
			get
			{
				return this.secnameField;
			}
			set
			{
				this.secnameField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string firstname
		{
			get
			{
				return this.firstnameField;
			}
			set
			{
				this.firstnameField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string fathersname
		{
			get
			{
				return this.fathersnameField;
			}
			set
			{
				this.fathersnameField = value;
			}
		}

		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Official
	{

		private string departmentField;

		private string postField;

		private string separatorField;

		private string valueField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string department
		{
			get
			{
				return this.departmentField;
			}
			set
			{
				this.departmentField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string post
		{
			get
			{
				return this.postField;
			}
			set
			{
				this.postField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string separator
		{
			get
			{
				return this.separatorField;
			}
			set
			{
				this.separatorField = value;
			}
		}

		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Rank
	{

		private string valueField;

		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class PrivatePerson
	{

		private Name nameField;

		private List<Rank> rankField;

		private Address addressField;

		private List<Econtact> econtactField;

		private ulong innField;

		private bool innFieldSpecified;

		private string doc_kindField;

		private string doc_numField;

		private string doc_orgField;

		private System.DateTime doc_dateField;

		private bool doc_dateFieldSpecified;

		public PrivatePerson()
		{
			this.econtactField = new List<Econtact>();
			this.addressField = new Address();
			this.rankField = new List<Rank>();
			this.nameField = new Name();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Name Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Rank", Order = 1)]
		public List<Rank> Rank
		{
			get
			{
				return this.rankField;
			}
			set
			{
				this.rankField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public Address Address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Econtact", Order = 3)]
		public List<Econtact> Econtact
		{
			get
			{
				return this.econtactField;
			}
			set
			{
				this.econtactField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong inn
		{
			get
			{
				return this.innField;
			}
			set
			{
				this.innField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool innSpecified
		{
			get
			{
				return this.innFieldSpecified;
			}
			set
			{
				this.innFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string doc_kind
		{
			get
			{
				return this.doc_kindField;
			}
			set
			{
				this.doc_kindField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string doc_num
		{
			get
			{
				return this.doc_numField;
			}
			set
			{
				this.doc_numField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string doc_org
		{
			get
			{
				return this.doc_orgField;
			}
			set
			{
				this.doc_orgField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime doc_date
		{
			get
			{
				return this.doc_dateField;
			}
			set
			{
				this.doc_dateField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool doc_dateSpecified
		{
			get
			{
				return this.doc_dateFieldSpecified;
			}
			set
			{
				this.doc_dateFieldSpecified = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class RegHistory
	{

		private OrganizationOnly organizationOnlyField;

		private RegNumber regNumberField;

		private string idnumberField;

		public RegHistory()
		{
			this.regNumberField = new RegNumber();
			this.organizationOnlyField = new OrganizationOnly();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public OrganizationOnly OrganizationOnly
		{
			get
			{
				return this.organizationOnlyField;
			}
			set
			{
				this.organizationOnlyField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public RegNumber RegNumber
		{
			get
			{
				return this.regNumberField;
			}
			set
			{
				this.regNumberField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string idnumber
		{
			get
			{
				return this.idnumberField;
			}
			set
			{
				this.idnumberField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Author
	{

		private List<object> itemsField;

		public Author()
		{
			this.itemsField = new List<object>();
		}

		[System.Xml.Serialization.XmlElementAttribute("OrganizationWithSign", typeof(OrganizationWithSign), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("OutNumber", typeof(OutNumber), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("PrivatePersonWithSign", typeof(PrivatePersonWithSign), Order = 0)]
		public List<object> Items
		{
			get
			{
				return this.itemsField;
			}
			set
			{
				this.itemsField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class OrganizationWithSign
	{

		private Address addressField;

		private List<Econtact> econtactField;

		private List<OfficialPersonWithSign> officialPersonWithSignField;

		private string organization_stringField;

		private string fullnameField;

		private string shortnameField;

		private string ownershipField;

		private ulong ogrnField;

		private bool ogrnFieldSpecified;

		private ulong innField;

		private bool innFieldSpecified;

		private ulong kppField;

		private bool kppFieldSpecified;

		public OrganizationWithSign()
		{
			this.officialPersonWithSignField = new List<OfficialPersonWithSign>();
			this.econtactField = new List<Econtact>();
			this.addressField = new Address();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Address Address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Econtact", Order = 1)]
		public List<Econtact> Econtact
		{
			get
			{
				return this.econtactField;
			}
			set
			{
				this.econtactField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("OfficialPersonWithSign", Order = 2)]
		public List<OfficialPersonWithSign> OfficialPersonWithSign
		{
			get
			{
				return this.officialPersonWithSignField;
			}
			set
			{
				this.officialPersonWithSignField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string organization_string
		{
			get
			{
				return this.organization_stringField;
			}
			set
			{
				this.organization_stringField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string fullname
		{
			get
			{
				return this.fullnameField;
			}
			set
			{
				this.fullnameField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string shortname
		{
			get
			{
				return this.shortnameField;
			}
			set
			{
				this.shortnameField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string ownership
		{
			get
			{
				return this.ownershipField;
			}
			set
			{
				this.ownershipField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong ogrn
		{
			get
			{
				return this.ogrnField;
			}
			set
			{
				this.ogrnField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool ogrnSpecified
		{
			get
			{
				return this.ogrnFieldSpecified;
			}
			set
			{
				this.ogrnFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong inn
		{
			get
			{
				return this.innField;
			}
			set
			{
				this.innField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool innSpecified
		{
			get
			{
				return this.innFieldSpecified;
			}
			set
			{
				this.innFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong kpp
		{
			get
			{
				return this.kppField;
			}
			set
			{
				this.kppField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool kppSpecified
		{
			get
			{
				return this.kppFieldSpecified;
			}
			set
			{
				this.kppFieldSpecified = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class OfficialPersonWithSign
	{

		private Name nameField;

		private List<Official> officialField;

		private List<Rank> rankField;

		private Address addressField;

		private List<Econtact> econtactField;

		private SignDate signDateField;

		public OfficialPersonWithSign()
		{
			this.signDateField = new SignDate();
			this.econtactField = new List<Econtact>();
			this.addressField = new Address();
			this.rankField = new List<Rank>();
			this.officialField = new List<Official>();
			this.nameField = new Name();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Name Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Official", Order = 1)]
		public List<Official> Official
		{
			get
			{
				return this.officialField;
			}
			set
			{
				this.officialField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Rank", Order = 2)]
		public List<Rank> Rank
		{
			get
			{
				return this.rankField;
			}
			set
			{
				this.rankField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 3)]
		public Address Address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Econtact", Order = 4)]
		public List<Econtact> Econtact
		{
			get
			{
				return this.econtactField;
			}
			set
			{
				this.econtactField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 5)]
		public SignDate SignDate
		{
			get
			{
				return this.signDateField;
			}
			set
			{
				this.signDateField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class SignDate
	{

		private System.DateTime valueField;

		[System.Xml.Serialization.XmlTextAttribute(DataType = "date")]
		public System.DateTime Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class OutNumber
	{

		private RegNumber regNumberField;

		public OutNumber()
		{
			this.regNumberField = new RegNumber();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public RegNumber RegNumber
		{
			get
			{
				return this.regNumberField;
			}
			set
			{
				this.regNumberField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class PrivatePersonWithSign
	{

		private Name nameField;

		private List<Rank> rankField;

		private Address addressField;

		private List<Econtact> econtactField;

		private SignDate signDateField;

		private ulong innField;

		private bool innFieldSpecified;

		private string doc_kindField;

		private string doc_numField;

		private string doc_orgField;

		private System.DateTime doc_dateField;

		private bool doc_dateFieldSpecified;

		public PrivatePersonWithSign()
		{
			this.signDateField = new SignDate();
			this.econtactField = new List<Econtact>();
			this.addressField = new Address();
			this.rankField = new List<Rank>();
			this.nameField = new Name();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Name Name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Rank", Order = 1)]
		public List<Rank> Rank
		{
			get
			{
				return this.rankField;
			}
			set
			{
				this.rankField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 2)]
		public Address Address
		{
			get
			{
				return this.addressField;
			}
			set
			{
				this.addressField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Econtact", Order = 3)]
		public List<Econtact> Econtact
		{
			get
			{
				return this.econtactField;
			}
			set
			{
				this.econtactField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 4)]
		public SignDate SignDate
		{
			get
			{
				return this.signDateField;
			}
			set
			{
				this.signDateField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public ulong inn
		{
			get
			{
				return this.innField;
			}
			set
			{
				this.innField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool innSpecified
		{
			get
			{
				return this.innFieldSpecified;
			}
			set
			{
				this.innFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string doc_kind
		{
			get
			{
				return this.doc_kindField;
			}
			set
			{
				this.doc_kindField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string doc_num
		{
			get
			{
				return this.doc_numField;
			}
			set
			{
				this.doc_numField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string doc_org
		{
			get
			{
				return this.doc_orgField;
			}
			set
			{
				this.doc_orgField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime doc_date
		{
			get
			{
				return this.doc_dateField;
			}
			set
			{
				this.doc_dateField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool doc_dateSpecified
		{
			get
			{
				return this.doc_dateFieldSpecified;
			}
			set
			{
				this.doc_dateFieldSpecified = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Validator
	{

		private object itemField;

		private string attestationField;

		[System.Xml.Serialization.XmlElementAttribute("DocNumber", typeof(DocNumber), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("OrganizationWithSign", typeof(OrganizationWithSign), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("PrivatePersonWithSign", typeof(PrivatePersonWithSign), Order = 0)]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string attestation
		{
			get
			{
				return this.attestationField;
			}
			set
			{
				this.attestationField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Writer
	{

		private object itemField;

		[System.Xml.Serialization.XmlElementAttribute("Organization", typeof(Organization), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("PrivatePerson", typeof(PrivatePerson), Order = 0)]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class TaskListTypeTask
	{

		private TaskNumber taskNumberField;

		private Confident confidentField;

		private List<Referred> referredField;

		private List<AuthorOrganization> authorOrganizationField;

		private List<DocTransfer> docTransferField;

		private List<Executor> executorField;

		private string idnumberField;

		private sbyte task_regField;

		private sbyte task_copyField;

		private string kindField;

		private string task_textField;

		private System.DateTime deadlineField;

		public TaskListTypeTask()
		{
			this.executorField = new List<Executor>();
			this.docTransferField = new List<DocTransfer>();
			this.authorOrganizationField = new List<AuthorOrganization>();
			this.referredField = new List<Referred>();
			this.confidentField = new Confident();
			this.taskNumberField = new TaskNumber();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public TaskNumber TaskNumber
		{
			get
			{
				return this.taskNumberField;
			}
			set
			{
				this.taskNumberField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public Confident Confident
		{
			get
			{
				return this.confidentField;
			}
			set
			{
				this.confidentField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Referred", Order = 2)]
		public List<Referred> Referred
		{
			get
			{
				return this.referredField;
			}
			set
			{
				this.referredField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("AuthorOrganization", Order = 3)]
		public List<AuthorOrganization> AuthorOrganization
		{
			get
			{
				return this.authorOrganizationField;
			}
			set
			{
				this.authorOrganizationField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("DocTransfer", Order = 4)]
		public List<DocTransfer> DocTransfer
		{
			get
			{
				return this.docTransferField;
			}
			set
			{
				this.docTransferField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Executor", Order = 5)]
		public List<Executor> Executor
		{
			get
			{
				return this.executorField;
			}
			set
			{
				this.executorField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string idnumber
		{
			get
			{
				return this.idnumberField;
			}
			set
			{
				this.idnumberField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte task_reg
		{
			get
			{
				return this.task_regField;
			}
			set
			{
				this.task_regField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte task_copy
		{
			get
			{
				return this.task_copyField;
			}
			set
			{
				this.task_copyField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string kind
		{
			get
			{
				return this.kindField;
			}
			set
			{
				this.kindField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string task_text
		{
			get
			{
				return this.task_textField;
			}
			set
			{
				this.task_textField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime deadline
		{
			get
			{
				return this.deadlineField;
			}
			set
			{
				this.deadlineField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class AuthorOrganization
	{

		private OrganizationWithSign organizationWithSignField;

		public AuthorOrganization()
		{
			this.organizationWithSignField = new OrganizationWithSign();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public OrganizationWithSign OrganizationWithSign
		{
			get
			{
				return this.organizationWithSignField;
			}
			set
			{
				this.organizationWithSignField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Executor
	{

		private Organization organizationField;

		private sbyte responsibleField;

		private bool responsibleFieldSpecified;

		private string task_specifiedField;

		private System.DateTime deadlineField;

		private bool deadlineFieldSpecified;

		public Executor()
		{
			this.organizationField = new Organization();
		}

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public Organization Organization
		{
			get
			{
				return this.organizationField;
			}
			set
			{
				this.organizationField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte responsible
		{
			get
			{
				return this.responsibleField;
			}
			set
			{
				this.responsibleField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool responsibleSpecified
		{
			get
			{
				return this.responsibleFieldSpecified;
			}
			set
			{
				this.responsibleFieldSpecified = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string task_specified
		{
			get
			{
				return this.task_specifiedField;
			}
			set
			{
				this.task_specifiedField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
		public System.DateTime deadline
		{
			get
			{
				return this.deadlineField;
			}
			set
			{
				this.deadlineField = value;
			}
		}

		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool deadlineSpecified
		{
			get
			{
				return this.deadlineFieldSpecified;
			}
			set
			{
				this.deadlineFieldSpecified = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class AddDocumentsTypeFolder
	{

		private List<DocTransfer> docTransferField;

		private List<Note> noteField;

		private List<Referred> referredField;

		private sbyte add_typeField;

		public AddDocumentsTypeFolder()
		{
			this.referredField = new List<Referred>();
			this.noteField = new List<Note>();
			this.docTransferField = new List<DocTransfer>();
		}

		[System.Xml.Serialization.XmlElementAttribute("DocTransfer", Order = 0)]
		public List<DocTransfer> DocTransfer
		{
			get
			{
				return this.docTransferField;
			}
			set
			{
				this.docTransferField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Note", Order = 1)]
		public List<Note> Note
		{
			get
			{
				return this.noteField;
			}
			set
			{
				this.noteField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("Referred", Order = 2)]
		public List<Referred> Referred
		{
			get
			{
				return this.referredField;
			}
			set
			{
				this.referredField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public sbyte add_type
		{
			get
			{
				return this.add_typeField;
			}
			set
			{
				this.add_typeField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class Note
	{

		private string valueField;

		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
	public partial class TaskListType
	{

		private List<TaskListTypeTask> taskField;

		public TaskListType()
		{
			this.taskField = new List<TaskListTypeTask>();
		}

		[System.Xml.Serialization.XmlElementAttribute("Task", Order = 0)]
		public List<TaskListTypeTask> Task
		{
			get
			{
				return this.taskField;
			}
			set
			{
				this.taskField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
	[System.SerializableAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
	public partial class AddDocumentsType
	{

		private List<AddDocumentsTypeFolder> folderField;

		public AddDocumentsType()
		{
			this.folderField = new List<AddDocumentsTypeFolder>();
		}

		[System.Xml.Serialization.XmlElementAttribute("Folder", Order = 0)]
		public List<AddDocumentsTypeFolder> Folder
		{
			get
			{
				return this.folderField;
			}
			set
			{
				this.folderField = value;
			}
		}
	}
}
